version: 2
updates:
  - package-ecosystem: nuget
    directory: bot/
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: bot/src/ChampionsOfKhazad.Bot.Portal/frontend
    schedule:
      interval: weekly
