<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ChampionsOfKhazad.Bot.Core\ChampionsOfKhazad.Bot.Core.csproj" />
    <ProjectReference Include="..\ChampionsOfKhazad.Bot.GenAi.Embeddings\ChampionsOfKhazad.Bot.GenAi.Embeddings.csproj" />
    <ProjectReference Include="..\ChampionsOfKhazad.Bot.Lore.Abstractions\ChampionsOfKhazad.Bot.Lore.Abstractions.csproj" />
  </ItemGroup>
</Project>
