using System.ComponentModel;
using ChampionsOfKhazad.Bot.Lore.Abstractions;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;

namespace ChampionsOfKhazad.Bot.GenAi;

internal class PersonalityTools(IGetRelatedLore relatedLoreGetter, ImageGenerationService imageGenerationService, ILogger<PersonalityTools> logger)
{
    public IList<AITool> Create(IMessageContext messageContext, bool includeLorekeeperTools)
    {
        var requestTools = new RequestTools(relatedLoreGetter, imageGenerationService, messageContext, logger);
        List<AITool> tools =
        [
            AIFunctionFactory.Create(
                requestTools.SearchLoreAsync,
                "search_lore",
                "Searches guild lore. Call this before answering a question that could refer to a guild member, player, character, name, nickname, alias, event, history, rule, or inside joke, including ambiguous terms with an outside meaning. Do not claim there is no relevant guild lore without searching first.",
                null
            ),
        ];

        if (!includeLorekeeperTools)
            return tools;

        tools.Add(
            AIFunctionFactory.Create(requestTools.GenerateImageAsync, "generate_image", "Generates an image from the supplied text prompt.", null)
        );
        tools.Add(
            AIFunctionFactory.Create(
                requestTools.SearchGeneratedImagesAsync,
                "search_generated_images",
                "Searches previously generated images by their prompt.",
                null
            )
        );

        return tools;
    }

    private sealed class RequestTools(
        IGetRelatedLore relatedLoreGetter,
        ImageGenerationService imageGenerationService,
        IMessageContext messageContext,
        ILogger logger
    )
    {
        [Description("Searches guild lore for details relevant to a question.")]
        public async Task<string> SearchLoreAsync(
            [Description("The question or terms to search for in guild lore.")] string query,
            CancellationToken cancellationToken
        )
        {
            try
            {
                var lore = await relatedLoreGetter.GetRelatedLoreAsync(query);

                return lore.Count == 0 ? "No relevant guild lore was found." : string.Join("\n---\n\n", lore.Select(entry => entry.ToString()));
            }
            catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
            {
                logger.LogInformation("Guild lore search was cancelled for Discord user {UserId}.", messageContext.UserId);
                throw;
            }
            catch (Exception exception)
            {
                logger.LogError(exception, "Guild lore search failed for Discord user {UserId}.", messageContext.UserId);
                return "Guild lore lookup failed. Tell the user that guild lore is temporarily unavailable; do not invent lore.";
            }
        }

        [Description("Generates an image from a text prompt.")]
        public Task<GenerateImageResult> GenerateImageAsync(
            [Description("The text prompt describing the image to generate.")] string prompt,
            CancellationToken cancellationToken
        ) => imageGenerationService.GenerateImageAsync(prompt, messageContext, cancellationToken);

        [Description("Searches previously generated images by their prompt.")]
        public Task<string> SearchGeneratedImagesAsync(
            [Description("The search text to match against image prompts.")] string searchText,
            [Description("When true, search only images generated by the current Discord user.")] bool onlyMine,
            CancellationToken cancellationToken
        ) => imageGenerationService.SearchGeneratedImagesAsync(searchText, onlyMine, messageContext, cancellationToken);
    }
}
