name: Deploy Bot

on:
  push:
    branches:
      - main
    paths:
      - bot/**

permissions:
  contents: read

concurrency: deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - name: Deploy Bot
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: prod
          work-dir: bot/src/ChampionsOfKhazad.Bot.Infrastructure/
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          COMMIT_SHA: ${{ github.sha }}
