name: Deploy Bot

on:
  push:
    branches:
      - main
    paths:
      - bot/**
      - global.json
      - .github/workflows/bot-deploy.yml

permissions:
  contents: read

concurrency: deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.x
      - run: dotnet build bot/ChampionsOfKhazad.Bot.slnx
      - run: dotnet test --solution bot/ChampionsOfKhazad.Bot.slnx --no-build --minimum-expected-tests 1
      - name: Deploy Bot
        uses: pulumi/actions@v7
        with:
          command: up
          stack-name: prod
          work-dir: bot/src/ChampionsOfKhazad.Bot.Infrastructure/
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
