name: Check Frontend

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check-frontend:
    name: Check Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot/src/ChampionsOfKhazad.Bot.Portal/frontend
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: bot/src/ChampionsOfKhazad.Bot.Portal/frontend/package-lock.json
      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm run build
